before_script:
  - docker pull maven:latest

variables:
  DOCKER_DRIVER: overlay2

stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy

maven-build-job:       # This job runs in the build stage, which runs first.
  image: maven:3.9.9-eclipse-temurin-21
  stage: build
  script:
    - mvn -v
    - cd timebridge
    - echo "Compiling the code..."
    - mvn clean package
  artifacts:
    paths:
        - timebridge/target/*.jar 


deploy-job:      # This job runs in the deploy stage.
  image: docker:latest
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  services:
    - name: docker:dind
  script:
    - cd timebridge
    - echo "Deploying application..."
    - docker build -t registry.git.chalmers.se/palssons/dit213-group-12 . -f /Dockerfile
    - echo "Login to gitlab..."
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.git.chalmers.se
    - echo "Pushing to gitlab..."
    - docker push registry.git.chalmers.se/palssons/dit213-group-12 
    - echo "Application successfully deployed."