services:
  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"

  spring-boot-app:
    build:
      context: ./timebridge
      dockerfile: Dockerfile
    environment:
    - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/timebridge
    depends_on:
      - mongodb
    ports:
      - "8080:8080"

  sveltekit-app:
    build:
      context: ./timebridge-web
      dockerfile: Dockerfile
    container_name: sveltekit-app
    ports:
      - "3000:3000"
